const INIT = "INIT";
const CANCEL = "CANCEL";
const STARTED = "STARTED";
const PASSED = "PASSED";
const COMPLETE = "COMPLETE";
const RESCHEDULE = "RESCHEDULE";
const UPDATE = "UPDATE";
const EDIT_NOTES = "EDIT_NOTES";
const IN_COMPLETE = "IN_COMPLETE";

export const STAGES = {
  INIT,
  CANCEL,
  STARTED,
  PASSED,
  COMPLETE,
  RESCHEDULE,
  UPDATE,
  EDIT_NOTES,
  IN_COMPLETE
};

export const ACTIVITIES = {
  FOLLOW_UP: {
    [INIT]: "FOLLOW_UP_INIT",
    [CANCEL]: "FOLLOW_UP_CANCEL",
    [STARTED]: "FOLLOW_UP_STARTED",
    [PASSED]: "FOLLOW_UP_PASSED",
    [IN_COMPLETE]: "FOLLOW_UP_IN_COMPLETE",
    [COMPLETE]: "FOLLOW_UP_COMPLETE",
    [RESCHEDULE]: "FOLLOW_UP_RESCHEDULE",
    [EDIT_NOTES]: "FOLLOW_UP_EDIT_NOTES",
    [UPDATE]: "FOLLOW_UP_UPDATE"
  },
  MATERIAL_DELIVERY: {
    [INIT]: "MATERIAL_DELIVERY_INIT",
    [CANCEL]: "MATERIAL_DELIVERY_CANCEL",
    [STARTED]: "MATERIAL_DELIVERY_STARTED",
    [PASSED]: "MATERIAL_DELIVERY_PASSED",
    [IN_COMPLETE]: "MATERIAL_DELIVERY_IN_COMPLETE",
    [COMPLETE]: "MATERIAL_DELIVERY_COMPLETE",
    [EDIT_NOTES]: "MATERIAL_DELIVERY_EDIT_NOTES",
    [RESCHEDULE]: "MATERIAL_DELIVERY_RESCHEDULE",
    [UPDATE]: "MATERIAL_DELIVERY_UPDATE"
  },
  MEDICATION: {
    [INIT]: "MEDICATION_INIT",
    [CANCEL]: "MEDICATION_CANCEL",
    [COMPLETE]: "MEDICATION_COMPLETE",
    [STARTED]: "MEDICATION_STARTED",
    [PASSED]: "MEDICATION_PASSED",
    [IN_COMPLETE]: "MEDICATION_IN_COMPLETE",
    [EDIT_NOTES]: "MEDICATION_EDIT_NOTES",
    [RESCHEDULE]: "MEDICATION_RESCHEDULE",
    [UPDATE]: "MEDICATION_UPDATE"
  },
  REMINDER: {
    [INIT]: "REMINDER_INIT",
    [STARTED]: "REMINDER_STARTED",
    [CANCEL]: "REMINDER_CANCEL",
    [COMPLETE]: "REMINDER_COMPLETE",
    [IN_COMPLETE]: "REMINDER_IN_COMPLETE",
    [RESCHEDULE]: "REMINDER_RESCHEDULE",
    [EDIT_NOTES]: "REMINDER_EDIT_NOTES",
    [UPDATE]: "REMINDER_UPDATE"
  },
  ADVERSE_EVENT: {
    [INIT]: "ADVERSE_EVENT_INIT",
    [CANCEL]: "ADVERSE_EVENT_CANCEL",
    [COMPLETE]: "ADVERSE_EVENT_COMPLETE",
    [UPDATE]: "ADVERSE_EVENT_UPDATE"
  }
};
