const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
const RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT";
const RESCHEDULE_THIS_APPOINTMENT = "RESCHEDULE_THIS_APPOINTMENT";
const RESCHEDULE_ALL_APPOINTMENT = "RESCHEDULE_ALL_APPOINTMENT";
const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
const EDIT_NOTES_OF_APPOINTMENT = "EDIT_NOTES_OF_APPOINTMENT";

const UPDATE_MEDICATION = "UPDATE_MEDICATION";
const UPADTE_VITALS = "UPDATE_VITALS";
const UPDATE_BASICS = "UPDATE_BASICS";
const UPDATE_CLINICAL_READING = "UPDATE_CLINICAL_READING";

const MARK_AS_DONE = "MARK_AS_DONE";
const UNDO = "UNDO";
const JOIN_CALL = "JOIN_CALL";

export const ACTIONS = {
  EDIT_APPOINTMENT,
  RESCHEDULE_ALL_APPOINTMENT,
  RESCHEDULE_THIS_APPOINTMENT,
  RESCHEDULE_APPOINTMENT,
  CANCEL_APPOINTMENT,
  EDIT_NOTES_OF_APPOINTMENT,
  UPADTE_VITALS,
  UPDATE_BASICS,
  UPDATE_MEDICATION,
  UPDATE_CLINICAL_READING,
  MARK_AS_DONE,
  UNDO,
  JOIN_CALL
};
