const ERROR_CODES = {
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  FORBIDDEN: "FORBIDDEN",
  PROGRAM_ADDITION_NOT_PERMISSIBLE: "PROGRAM_ADDITION_NOT_PERMISSIBLE",
  ADDITION_TO_PROGRAM_NOT_PERMISSIBLE: "ADDITION_TO_PROGRAM_NOT_PERMISSIBLE",
  EXISTING_USER: "EXISTING_USER",
  EVENT_EXPIRED: "EVENT_EXPIRED",
  LINK_ALREADY_USED: "LINK_ALREADY_USED",
  EVENT_WAS_CANCELLED: "EVENT_WAS_CANCELLED",
  INVALID_LINK: "INVALID_LINK",
  COOKIES_NOT_SET: "COOKIES_NOT_SET",
  CONTACT_ALREADY_EXISTS: "CONTACT_ALREADY_EXISTS",
  CAN_NOT_AUTHORIZE: "CAN_NOT_AUTHORIZE",
  PASSWORD_MISMATCH_ERROR: "PASSWORD_MISMATCH_ERROR",
  INVITE_NOT_PERMISSIBLE: "INVITE_NOT_PERMISSIBLE",
  OTP_MISMATCH: "OTP_MISMATCH",
  IMAGE_NOT_SAVED: "IMAGE_NOT_SAVED",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD"
};

module.exports = {
  ERROR_CODES
};
