export default {
  CALENDAR_SYNC: JSON.parse(process.env.REACT_APP_CALENDAR_SYNC),
  BASE_DOC_URL: process.env.REACT_APP_IMAGE_HOST,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  GETSTREAM_API_KEY: process.env.REACT_APP_GETSTREAM_API_KEY,
  GETSTREAM_APP_ID: process.env.REACT_APP_GETSTREAM_APP_ID
};
