const EDIT_REMINDER = "EDIT_REMINDER";
const RESCHEDULE_REMINDER = "RESCHEDULE_REMINDER";
const RESCHEDULE_THIS_REMINDER = "RESCHEDULE_THIS_REMINDER";
const RESCHEDULE_ALL_REMINDER = "RESCHEDULE_ALL_REMINDER";
const CANCEL_REMINDER = "CANCEL_REMINDER";
const EDIT_NOTES_OF_REMINDER = "EDIT_NOTES_OF_REMINDER";

export const ACTIONS = {
  EDIT_REMINDER,
  EDIT_NOTES_OF_REMINDER,
  RESCHEDULE_REMINDER,
  RESCHEDULE_ALL_REMINDER,
  RESCHEDULE_THIS_REMINDER,
  CANCEL_REMINDER
};
