const constants = {
  APPOINTMENT: "appointment",
  APPOINTMENT_CREATE: "appointment create",
  APPOINTMENT_UPDATE: "appointment update",
  APPOINTMENT_NOW: "appointment now",
  APPOINTMENT_PRIOR: "appointment prior",
  REMINDER: "reminder",
  REMINDER_CREATE: "reminder create",
  REMINDER_UPDATE: "reminder update",
  REMINDER_NOW: "reminder now",
  SURVEY: "survey",
  SURVEY_CREATE: "survey create",
  SURVEY_UPDATE: "survey update",
  ADVERSE_EVENT: "adverse event",
  ADVERSE_EVENT_CREATE: "adverse event create",
  VITALS: "vitals",
  VITALS_SELF_CREATE: "vitals self create",
  VITALS_SELF_DELETE: "vitals self delete",
  VITALS_SELF_UPDATE: "vitals self update",
  VITALS_CREATE: "vitals create",
  VITALS_DELETE: "vitals delete",
  VITALS_UPDATE: "vitals update",
  ARTICLE: "article",
  ARTICLE_CREATE: "article create",
  ARTICLE_UPDATE: "article update",
  PRESCRIPTION: "prescription",
  PRESCRIPTION_CREATE: "prescription create",
  PRESCRIPTION_UPDATE: "prescription update",
  PROGRAM: "program",
  PROGRAM_CREATE: "program create",
  PROGRAM_UPDATE: "program update"
};

module.exports = constants;
